@echo off

if not defined murgi echo [41;97mYou can't open me directly[0m :P & cmd /k

set "autoOpenMCPACK=.settings\autoOpenMCPACK.txt"
set "backupDate=.settings\backupDate.txt"
set "customMinecraftAppPath=.settings\customMinecraftAppPath.txt"
set "customMinecraftDataPath=.settings\customMinecraftDataPath.txt"
set "customIObitUnlockerPath=.settings\customIObitUnlockerPath.txt"
set "defaultgamedata=%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang"
set "defaultMethod=.settings\defaultMethod.txt"
set "disableConfirmation=.settings\disableConfirmation.txt"
set "disableInterruptionCheck=.settings\disableInterruptionCheck.txt"
set "disableMatCompatCheck=.settings\disableMatCompatCheck.txt"
set "disableRetainOldBackups=.settings\disableRetainOldBackups.txt"
set "disableSuccessMsg=.settings\disableSuccessMsg.txt"
set "doCheckUpdates=.settings\doCheckUpdates.txt"
set "gamedata=%defaultgamedata%"
set "matbak=Backups\Materials (backup)"
set "materialUpdaterArg=.settings\materialUpdaterArg.txt"
set "matjectNEXTenabled=.settings\matjectNEXTenabled.txt"
set "oldMinecraftVersion=.settings\oldMinecraftVersion.txt"
set "ranOnce=.settings\ranOnce.txt"
set "syncThenExit=.settings\syncThenExit.txt"
set "thanksMcbegamerxx954=.settings\thanksMcbegamerxx954.txt"
set "unlocked=.settings\unlockedWindowsApps.txt"

set "backmsg=echo. && echo Press any key to go back... && pause > NUL && goto:EOF"
set "exitmsg=echo. && echo Press any key to exit... && pause > NUL && exit"
set "uacfailed=echo %ERR%[^^^^^!] Please accept UAC.%RST% && echo. && echo Press any key to try again... && echo. && pause >nul"